name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: 'x64'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Send APK to Telegram
      run: |
        curl -F document=@app/build/outputs/apk/debug/app-debug.apk \
             -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
             -F caption="✅ Android APK is ready! (Built from GitHub Actions)" \
             https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument
