name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: 'x64'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: build/outputs/apk/debug/app-debug.apk

    - name: List APK files
      run: find . -name "*.apk"

    - name: Send APK to Telegram
      run: |
        curl -F document=@build/outputs/apk/debug/android-gradle-java-app-template-debug.apk \
             -F chat_id=7315149418 \
             -F caption="✅ Android APK is ready! (Build from GitHub Actions)" \
             https://api.telegram.org/bot7561020315:AAF4SVaKflzB0SvY3pjQ8tWNfuQe2AcmpDo/sendDocument
