name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  JAVA_VERSION: 20 # can't use Java 21 yet due to mockito issues
  ANDROID_API_LEVEL: 34

jobs:
  android:
    name: Android API ${{ matrix.api-level }} / JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.1

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2.1.1

      - name: Configure JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - run: ./gradlew --version

      - name: Build Debug APK
        run: ./gradlew assembleDebug -s

      - name: Run Debug Lint Checks
        run: ./gradlew lintDebug -s

      - name: Run Debug Unit Tests
        run: ./gradlew testDebug -s
